# Site settings
title: My Final Ruby Project
header-img: img/home-bg.png
email: marcussimon12082015@hotmail.com
copyright_name: marcusSimon12082015
description: > # this means to ignore newlines until "baseurl:"
  Scraping, Scraping
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcusSimon12082015
learn_profile: marcusSimon12082015
email_username: marcussimon12082015@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
